# @package _global_
defaults:
  - data: recommnedataion
  - test: recommnedataion
  - system: system

framework: pytorch
task: recommnedataion
model_path: models/model_id/20201013_13_17_10
test_id: test
  
hydra:
  run:
    dir: ${MODEL_PATH}/result/${TEST_ID} #${now:%Y%m%d_%H_%M_%S}
  sweep:
    dir: ${MODEL_PATH}/result/
    subdir: ${TEST_ID} #${now:%Y%m%d_%H_%M_%S}
